// Central data store for all articles
export const ALL_ARTICLES = [
  {
    slug: 'habibi-tacos',
    title: 'Introducing Habibi Tacos',
    subtitle: 'A Bold New Twist on a Classic Favorite',
    category: 'New on the Menu',
    date: 'June 2026',
    readTime: '4 min read',
    image: '/images/articles/habibi-taco-hero.jpg',
    excerpt: `At Habibi Halal Express, we believe that great food starts with great ingredients. That's exactly what inspired us to create Habibi Tacos — our signature take on one of the world's most loved street foods.`,
    featured: true,
  },
  {
    slug: 'lamb-kofta-secret',
    title: 'The Secret Behind Our Lamb Kofta',
    subtitle: 'From Spice to Flame — How We Make the Bronx\'s Best Kofta',
    category: 'Food Story',
    date: 'May 2026',
    readTime: '5 min read',
    image: '/images/food/shesh-kebab.jpg',
    excerpt: `Every Habibi Kofta starts with the same question our pitmaster asks every morning: is the blend right? Here's the full story behind our most iconic dish and the care that goes into every skewer.`,
    featured: false,
  },
  {
    slug: 'build-your-own',
    title: 'Build Your Own: The Bronx\'s Most Customizable Meal',
    subtitle: 'How We Created a Menu Feature That Changed Everything',
    category: 'Behind the Menu',
    date: 'April 2026',
    readTime: '4 min read',
    image: '/images/byo/customize-hero.jpg',
    excerpt: `When we launched Build Your Own, we didn't know it would become our most-ordered experience. Here's the story of how it came to be — and why it's more than just a meal builder.`,
    featured: false,
  },
  {
    slug: 'halal-certified',
    title: 'Halal Certified: What It Means and Why It Matters to Us',
    subtitle: 'Our Commitment to Standards You Can Trust',
    category: 'Our Values',
    date: 'March 2026',
    readTime: '6 min read',
    image: '/images/logos/halal-certified-premium.webp',
    excerpt: `Halal isn't just a label at Habibi — it's a promise. We break down exactly what our certification means, how we maintain it, and why we believe it makes our food better for everyone.`,
    featured: false,
  },
  // Cards linking to existing sub-pages
  {
    slug: null,
    externalPath: '/kitchen-behind-the-scenes',
    title: 'Kitchen Behind the Scenes',
    subtitle: 'Go Inside Our Kitchen and See How We Cook',
    category: 'Behind the Scenes',
    date: 'Ongoing',
    readTime: 'Video + Story',
    image: '/images/food/kitchen-hero.png',
    excerpt: `Real food. Real people. No shortcuts. Come inside our kitchen and see exactly how we craft every dish — from the first cut to the final plate.`,
    featured: false,
  },
  {
    slug: null,
    externalPath: '/customer-stories',
    title: 'Customer Stories',
    subtitle: 'Real Voices From the Bronx Community',
    category: 'Community',
    date: 'Ongoing',
    readTime: 'Stories',
    image: '/images/food/stories-hero.png',
    excerpt: `Hear from the real people who make Habibi Halal Express what it is. Thousands of orders, one community, and stories that keep us going every single day.`,
    featured: false,
  },
  {
    slug: null,
    externalPath: '/our-journey',
    title: 'Our Journey: From One Window to Three Locations',
    subtitle: 'The Story of Habibi Halal Express',
    category: 'Our Story',
    date: 'Est. 2018',
    readTime: '7 min read',
    image: '/images/food/journey-hero.png',
    excerpt: `From a single window in Bedford Park to three locations across the Bronx — this is how Habibi Halal Express came to be, and where we're headed next.`,
    featured: false,
  },
];
