--
-- PostgreSQL database dump
--

\restrict lds7PO5Qgi97BZaA97yDyFo5Won7dxBUf4eBsrvC5yyymabgvVNwvtWIoS1ALVM

-- Dumped from database version 18.4
-- Dumped by pg_dump version 18.4

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Data for Name: categories; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.categories VALUES (8, 'Breakfast', NULL, 0, true, NULL);
INSERT INTO public.categories VALUES (9, 'Platter', NULL, 0, true, NULL);
INSERT INTO public.categories VALUES (10, 'Sandwich', NULL, 0, true, NULL);
INSERT INTO public.categories VALUES (11, 'Tacos', NULL, 0, true, NULL);
INSERT INTO public.categories VALUES (12, 'Build Your Own', NULL, 0, true, NULL);
INSERT INTO public.categories VALUES (13, 'Extras', NULL, 0, true, NULL);


--
-- Data for Name: menu_items; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.menu_items VALUES (178, 'Habibi Breakfast Platter', 'Two eggs any style, beef sausage, halal turkey, toast, and home fries.', NULL, 14.99, 12.99, 8, 1, true, NULL, NULL, NULL);
INSERT INTO public.menu_items VALUES (179, 'Egg & Cheese on a Roll', 'Two fresh eggs with melted cheese on a toasted hard roll.', NULL, 6.99, 5.99, 8, 1, true, NULL, NULL, NULL);
INSERT INTO public.menu_items VALUES (180, 'Beef Sausage, Egg & Cheese', 'Halal beef sausage patty, scrambled eggs, and American cheese.', NULL, 8.99, 7.99, 8, 1, true, NULL, NULL, NULL);
INSERT INTO public.menu_items VALUES (181, 'Chicken & Waffle', 'Crispy halal fried chicken on a golden waffle with maple syrup.', NULL, 13.99, 11.99, 8, 1, true, NULL, NULL, NULL);
INSERT INTO public.menu_items VALUES (182, 'Steak & Egg Wrap', 'Thinly sliced halal steak, scrambled eggs, peppers, and onions in a flour tortilla.', NULL, 12.99, 10.99, 8, 1, true, NULL, NULL, NULL);
INSERT INTO public.menu_items VALUES (183, 'Lamb Shawarma Plate', 'Slow-roasted spiced lamb over saffron rice with garlic sauce, pickles, and salad.', NULL, 18.99, 16.99, 9, 1, true, NULL, NULL, NULL);
INSERT INTO public.menu_items VALUES (184, 'Chicken Kofta Plate', 'Seasoned ground chicken kofta skewers over rice pilaf with tzatziki.', NULL, 16.99, 14.99, 9, 1, true, NULL, NULL, NULL);
INSERT INTO public.menu_items VALUES (185, 'Mixed Grill Platter', 'Lamb kofta, chicken shish, and beef kebab over rice with grilled vegetables.', NULL, 24.99, 21.99, 9, 1, true, NULL, NULL, NULL);
INSERT INTO public.menu_items VALUES (186, 'Gyro Over Rice', 'Thinly sliced halal gyro meat over seasoned rice with white and hot sauce.', NULL, 15.99, 13.99, 9, 1, true, NULL, NULL, NULL);
INSERT INTO public.menu_items VALUES (187, 'Falafel Plate', 'Six crispy falafel balls over hummus and rice with tahini sauce and pita.', NULL, 13.99, 11.99, 9, 1, true, NULL, NULL, NULL);
INSERT INTO public.menu_items VALUES (188, 'Chicken Over Rice', 'Habibi signature chicken over yellow rice with lettuce, tomato, white sauce, and hot sauce.', NULL, 14.99, 12.99, 9, 1, true, NULL, NULL, NULL);
INSERT INTO public.menu_items VALUES (189, 'Shrimp Platter', 'Seasoned jumbo shrimp over garlic herb rice with lemon and garlic aioli.', NULL, 19.99, 17.99, 9, 1, true, NULL, NULL, NULL);
INSERT INTO public.menu_items VALUES (190, 'Chicken Shawarma Wrap', 'Marinated chicken shawarma in a warm pita with garlic paste, pickles, and fries.', NULL, 12.99, 10.99, 10, 1, true, NULL, NULL, NULL);
INSERT INTO public.menu_items VALUES (191, 'Beef Gyro Wrap', 'Sliced halal beef gyro in a flatbread with lettuce, tomato, onion, and tzatziki.', NULL, 12.99, 10.99, 10, 1, true, NULL, NULL, NULL);
INSERT INTO public.menu_items VALUES (192, 'Habibi Cheesesteak', 'Thinly sliced halal ribeye, sautéed peppers and onions, provolone, on a hoagie roll.', NULL, 14.99, 12.99, 10, 1, true, NULL, NULL, NULL);
INSERT INTO public.menu_items VALUES (193, 'Crispy Chicken Sandwich', 'Hand-breaded crispy halal chicken breast, pickles, and spicy mayo on a brioche bun.', NULL, 13.99, 11.99, 10, 1, true, NULL, NULL, NULL);
INSERT INTO public.menu_items VALUES (194, 'Lamb Burger', 'Seasoned ground lamb patty with lettuce, tomato, caramelized onion, and harissa aioli.', NULL, 15.99, 13.99, 10, 1, true, NULL, NULL, NULL);
INSERT INTO public.menu_items VALUES (195, 'Falafel Wrap', 'Crispy falafel, mixed greens, tomato, tahini, and pickled turnip in a warm pita.', NULL, 10.99, 9.49, 10, 1, true, NULL, NULL, NULL);
INSERT INTO public.menu_items VALUES (196, 'Lamb Kofta Tacos (2)', 'Two soft corn tortillas with spiced lamb kofta, pickled red onion, and cilantro crema.', NULL, 11.99, 9.99, 11, 1, true, NULL, NULL, NULL);
INSERT INTO public.menu_items VALUES (197, 'Chicken Shawarma Tacos (2)', 'Marinated chicken shawarma in flour tortillas with cabbage slaw and garlic sauce.', NULL, 10.99, 8.99, 11, 1, true, NULL, NULL, NULL);
INSERT INTO public.menu_items VALUES (198, 'Beef Barbacoa Tacos (2)', 'Slow-cooked spiced halal beef in corn tortillas with diced onion and fresh cilantro.', NULL, 12.99, 10.99, 11, 1, true, NULL, NULL, NULL);
INSERT INTO public.menu_items VALUES (199, 'Crispy Shrimp Tacos (2)', 'Crispy seasoned shrimp, avocado crema, mango salsa, and pickled jalapeños.', NULL, 13.99, 11.99, 11, 1, true, NULL, NULL, NULL);
INSERT INTO public.menu_items VALUES (200, 'Gyro Tacos (2)', 'Sliced halal gyro meat in warm pita tortillas with tzatziki and diced tomato.', NULL, 11.99, 9.99, 11, 1, true, NULL, NULL, NULL);
INSERT INTO public.menu_items VALUES (201, 'Build Your Own Bowl', 'Choose your base, protein, toppings, and sauce. Fully customized to your taste.', NULL, 13.99, 11.99, 12, 1, true, NULL, NULL, NULL);
INSERT INTO public.menu_items VALUES (202, 'Build Your Own Wrap', 'Pick your protein, veggies, and sauce wrapped in a fresh flour tortilla or pita.', NULL, 12.99, 10.99, 12, 1, true, NULL, NULL, NULL);
INSERT INTO public.menu_items VALUES (203, 'Build Your Own Platter', 'Choose two proteins, your base, two sides, and two sauces.', NULL, 17.99, 15.99, 12, 1, true, NULL, NULL, NULL);
INSERT INTO public.menu_items VALUES (204, 'Habibi Fries', 'Crispy seasoned fries with our signature Habibi spice blend.', NULL, 4.99, 3.99, 13, 1, true, NULL, NULL, NULL);
INSERT INTO public.menu_items VALUES (205, 'Cheese Fries', 'Golden fries smothered in melted cheddar cheese sauce.', NULL, 6.99, 5.99, 13, 1, true, NULL, NULL, NULL);
INSERT INTO public.menu_items VALUES (206, 'Hummus & Pita', 'Creamy house-made hummus with warm pita bread and olive oil drizzle.', NULL, 6.99, 5.99, 13, 1, true, NULL, NULL, NULL);
INSERT INTO public.menu_items VALUES (207, 'Side Salad', 'Mixed greens, tomato, cucumber, red onion, and lemon-herb vinaigrette.', NULL, 4.99, 3.99, 13, 1, true, NULL, NULL, NULL);
INSERT INTO public.menu_items VALUES (208, 'Rice (Side)', 'Seasoned yellow rice with herbs.', NULL, 3.99, 2.99, 13, 1, true, NULL, NULL, NULL);
INSERT INTO public.menu_items VALUES (209, 'Extra Sauce', 'White sauce, hot sauce, tahini, garlic paste, or tzatziki.', NULL, 1.49, 0.99, 13, 1, true, NULL, NULL, NULL);
INSERT INTO public.menu_items VALUES (210, 'Mozzarella Sticks (4)', 'Crispy breaded mozzarella sticks with marinara dipping sauce.', NULL, 7.99, 6.99, 13, 1, true, NULL, NULL, NULL);
INSERT INTO public.menu_items VALUES (211, 'Onion Rings', 'Thick-cut battered onion rings, perfectly golden and crispy.', NULL, 5.99, 4.99, 13, 1, true, NULL, NULL, NULL);


--
-- Data for Name: addon_groups; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- Data for Name: addon_options; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- Data for Name: choice_groups; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- Data for Name: choice_options; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- Data for Name: menus; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.menus VALUES (877, 'Cream Chesse Sandwich (Bagel / Roll / Croissant / Hero / More..)', 'Fresh backed today Bagel, Roll or your preferred kind of bread with our fresh Cream Cheese  (It''s the Coffee Favor to make it a Breakfast)', 'Breakfast at YOUR OWN TIME', 2.99, '/images/menu/35f.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (878, 'Eggs Sandwich (Bagel / Roll / Croissant / Hero / Pita / More..)', 'Two Grilled Eggs with Vegetable Salad in your preferred kind of bread with the Sauce of your choice', 'Breakfast at YOUR OWN TIME', 2.99, '/images/menu/36.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (879, 'Eggs & Cheese Sandwich (Bagel / Roll / Croissant / Hero / Pita / More..)', 'Two Grilled Eggs and Cheese with Vegetable Salad in your preferred kind of bread  with the Sauce of your choice', 'Breakfast at YOUR OWN TIME', 3.99, '/images/menu/37.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (880, 'Eggs & Halal Bacon Sandwich (Bagel / Roll / Croissant / Hero / Pita / More..)', 'Two Grilled Eggs and Cheese with Halal Cured Sliced Beef or Turkey Bacon and Vegetable Salad in your preferred kind of bread with the Sauce of your choice', 'Breakfast at YOUR OWN TIME', 5.99, '/images/menu/37b.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (881, 'Eggs & Beef Berger Sandwich (Bun / Bagel / More..)', 'Two Grilled Eggs and Beef Berger with Vegetable Salad in your preferred kind of bread with the Sauce of your choice', 'Breakfast at YOUR OWN TIME', 7.99, '/images/menu/38.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (882, 'Eggs & Hot Dog Sandwich (Bun / Bagel / Croissant / Pita / More..)', 'Two Grilled Eggs and Pieces of a Beef Hot Dog with Vegetable Salad in your preferred kind of bread with the Sauce of your choice', 'Breakfast at YOUR OWN TIME', 5.50, '/images/menu/39.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (883, 'Eggs & Sausage Sandwich  (Bun / Bagel / Croissant / Pita / More..)', 'Two Grilled Eggs and Pieces of a Seasoned Beef Hot Sausage with Vegetable Salad in your preferred kind of bread with the Sauce of your choice', 'Breakfast at YOUR OWN TIME', 6.99, '/images/menu/40.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (884, 'Eggs & Cheese & Sausage Sandwich (Bun / Bagel / Croissant / Pita / More..)', 'Two Grilled Eggs and Pieces of a Seasoned Beef Hot Sausage with Vegetable Salad in your preferred kind of bread with the Sauce of your choice', 'Breakfast at YOUR OWN TIME', 6.99, '/images/menu/40a.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (885, 'Eggs & Italian Sausage Sandwich (Bun / Bagel / Croissant / Pita / Hero / More..)', 'Two Grilled Eggs and Pieces of an Extra Large Seasoned Beef Italian Sausage with Vegetable Salad Wrapped in your preferred kind of bread with the Sauce of your choice', 'Breakfast at YOUR OWN TIME', 8.99, '/images/menu/41.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (886, '-Tuna Fish Salad Sandwich (Pita / Hero / Roll / More..)', 'Our Special homemade fresh Tuna Fish with  with Vegetable Salad  in the bread of your choice', 'Breakfast at YOUR OWN TIME', 8.49, '/images/menu/0h2.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (887, '-Tuna Fish Egg Salad Melt Deluxe Sandwich (Pita / Hero / Roll / More..)', 'Grilled Eggs Over Our Special homemade fresh Tuna Fish with Vegetable Salad  in the bread of your choice', 'Breakfast at YOUR OWN TIME', 9.99, '/images/menu/0h3.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (888, '-Tuna Fish Salad over Turkey  Sandwich (Pita / Hero / Roll / More..)', 'Slices of Bold Salsalito Turkey Breast Over Our Special homemade fresh Tuna Fish with Vegetable Salad  in the bread of your choice', 'Breakfast at YOUR OWN TIME', 10.99, '/images/menu/0h4.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (889, '-Turkey  Sandwich (Pita / Hero / Roll / More..)', 'Slices of Bold Salsalito Turkey Breast with  Vegetable Salad in  the bread of your choice', 'Breakfast at YOUR OWN TIME', 8.99, '/images/menu/0h5.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (890, '-Turkey  with Halal Bacon Sandwich (Pita / Hero / Roll / More..)', 'Slices of Bold Salsalito Turkey Breast with Halal Cured Sliced Beef or Turkey Bacon served with Onion, Green Peppers, lettuces, tomatoes, cucumber, and the Sauce of your choice and  the bread of your choice', 'Breakfast at YOUR OWN TIME', 8.99, '/images/menu/0h6.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (891, 'Chopped Cheese Sandwich', 'Chopped Grilled Halal Beef Berger with American Cheese in a Hero and the Sauce of your choice', 'Breakfast at YOUR OWN TIME', 7.99, '/images/menu/35c.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (892, 'Halal Bacon Sandwich (PLT) (Bagel / Roll / Croissant / Hero / Pita / More..)', 'Halal Cured Sliced Beef or Turkey Bacon with or without American Cheese in your preferred kind of bread with the Sauce of your choice', 'Breakfast at YOUR OWN TIME', 5.99, '/images/menu/35d.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (893, 'Halal Bacon and Sausage Sandwich (Bagel / Roll / Croissant / Hero / Pita / More..)', 'Halal Cured Sliced Beef or Turkey Bacon with Pieces of a Seasoned Beef Hot Sausage with the bread and the Sauce of your choic', 'Breakfast at YOUR OWN TIME', 7.99, '/images/menu/35e.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (894, 'Falafel Sandwich (Pita / Hero / More..)', 'Eight Piecial Homemade crispy fresh Falafel Wrapped in your preferred kind of bread and with the Sauce of your choice', 'Breakfast at YOUR OWN TIME', 7.99, '/images/menu/28.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (895, 'Falafel Salad Plate', 'Eight Pieces of our special Homemade crispy fresh Falafel served with lettuces, tomatoes, cucumber, and the Sauce of your choice', 'Breakfast at YOUR OWN TIME', 8.99, '/images/menu/15.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (896, 'Eggs & Cheese & Salad Plate', 'Two Grilled Eggs and Cheese served with Onion, Green Peppers, lettuces, tomatoes, cucumber, and the Sauce of your choice', 'Breakfast at YOUR OWN TIME', 5.99, '/images/menu/20.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (897, 'Eggs s& Beef Berger & Salad Plate', 'Two Grilled Eggs and Beef Berger served with Onion, Green Peppers, lettuces, tomatoes, cucumber, and the Sauce of your choice', 'Breakfast at YOUR OWN TIME', 8.99, '/images/menu/21.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (898, 'Eggs & Hot Dog & Salad Plate', 'Two Grilled Eggs with Pieces of Beef Hot Dog served with Onion, Green Peppers, lettuces, tomatoes, cucumber, and the Sauce of your choice', 'Breakfast at YOUR OWN TIME', 7.99, '/images/menu/22.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (899, 'Halal Bacon and Sausage Salad Plate', 'Two Grilled Eggs and Cheese with Halal Cured Sliced Beef or Turkey Bacon served with Onion, Green Peppers, lettuces, tomatoes, cucumber, and the Sauce of your choice', 'Breakfast at YOUR OWN TIME', 8.99, '/images/menu/22b.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (900, 'Eggs & Hot Sausage & Salad Plate', 'Two Grilled Eggs with Pieces of Beef Hot Sausage served with Onion, Green Peppers, lettuces, tomatoes, cucumber, and the Sauce of your choice', 'Breakfast at YOUR OWN TIME', 8.49, '/images/menu/23.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (901, 'Eggs & Italian Sausage & Salad Plate', 'Two Grilled Eggs with Pieces of Large Beef Italian Sausage served with Onion, Green Peppers, lettuces, tomatoes, cucumber, and the Sauce of your choice', 'Breakfast at YOUR OWN TIME', 9.99, '/images/menu/24.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (902, 'Mix Green Salad Plate', 'A Fresh Healthy Large Plate with a delicious mix of lettuces, tomatoes, cucumber, Onions, Green Peppers, and the Sauce of your choice', 'Breakfast at YOUR OWN TIME', 5.99, '/images/menu/7.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (903, 'Donut', 'Select Between Varity of Fresh Backed Today Donuts!', 'Breakfast at YOUR OWN TIME', 1.99, '/images/menu/49d.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (904, 'Dozen Donuts', 'A Mix of 12 Fresh  Backed Today Donuts', 'Breakfast at YOUR OWN TIME', 13.99, '/images/menu/49d2.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (905, 'Croissant', 'fresh Backed today Croissant', 'Breakfast at YOUR OWN TIME', 2.49, '/images/menu/49e.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (906, 'Muffin', 'fresh Backed today Muffin of your choice', 'Breakfast at YOUR OWN TIME', 2.99, '/images/menu/49f.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (907, 'Danish', 'Fresh Backed Today Danish of your Choice between Cheese and Cinnamon Kind', 'Breakfast at YOUR OWN TIME', 2.99, '/images/menu/49g.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (908, 'Apple Turnover', 'A pastry dessert filled with pieces of sweetened apples and Freshly Backed Today', 'Breakfast at YOUR OWN TIME', 2.99, '/images/menu/49h.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (909, 'Chicken over Rice', 'Grilled chicken chunks served over rice with vegetable salad and the Sauce of your choice', 'Platter', 9.99, '/images/menu/1.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (910, 'Chicken Salad', 'Grilled chicken chunks served with lettuces, tomatoes, cucumber, and the Sauce of your choice', 'Platter', 9.99, '/images/menu/2.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (911, 'Chicken Fries', 'Grilled chicken chunks served with our Special French Seasoned Fries, and the Sauce of your choice', 'Platter', 9.99, '/images/menu/2a.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (912, 'Lamp over Rice', 'Lamp Gyro Slices just came off the Rotating Gyro Machine now served over rice with vegetable salad and the Sauce of your choice', 'Platter', 9.99, '/images/menu/3.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (913, 'Lamp Salad', 'Lamp Gyro Slices just came off the Rotating Gyro Machine served with lettuces, tomatoes, cucumber, and the Sauce of your choice', 'Platter', 9.99, '/images/menu/4.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (914, 'Lamp Fries', 'Lamp Gyro Slices just came off the Rotating Gyro Machine served with our Special French Seasoned Fries, and the Sauce of your choice', 'Platter', 9.99, '/images/menu/4a.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (915, 'Combo (lamp & Chicken) over Rice', 'Grilled Chunks of Chicken and Lamp Gyro served over rice with vegetable salad and the Sauce of your choice', 'Platter', 10.99, '/images/menu/5.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (916, 'Combo (lamp & Chicken) Salad', 'Grilled Chunks of Chicken and Lamp Gyro served with lettuces, tomatoes, cucumber, and the Sauce of your choice', 'Platter', 10.99, '/images/menu/9.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (917, 'Combo (lamp & Chicken) Fries', 'Grilled Chunks of Chicken and Lamp Gyro served with our Special French Seasoned Fries, the Sauce of your choice', 'Platter', 10.99, '/images/menu/6a.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (918, 'Half Chicken Over Rice', 'Our Grilled Specially Seasoned Large Half Chicken on the bone served over rice with vegetable salad and the Sauce of your choice', 'Platter', 14.99, '/images/menu/6b.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (919, 'Half Grilled Chicken Salad', 'Our Grilled Specially Seasoned Large Half Chicken on the bone served with lettuces, tomatoes, cucumber, +F46+C51:F51+D51:F51+C51:F51+F46+C51:F51', 'Platter', 14.99, '/images/menu/6c.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (920, 'Mix Green Salad', 'A Fresh Healthy Large Plate with a delicious mix of lettuces, tomatoes, cucumber, Onions, Green Peppers, and the Sauce of your choice', 'Platter', 5.99, '/images/menu/7.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (921, 'Jumbo Shrimp Over Rice', 'Fried  Fresh Jumbo Shrimp Pieces Cooked with our special charcoal flavor and served over rice with vegetable salad and the Sauce of your choice', 'Platter', 10.99, '/images/menu/7b.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (922, 'Jumbo Shrimp Fries', 'Six Fried  Fresh Jumbo Shrimp Pieces Cooked with our special charcoal flavor and served with our special French Fries and the Sauce of your choice', 'Platter', 10.99, '/images/menu/7c.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (923, 'Jumbo Shrimp Salad', 'Six Grilled Fresh Jumbo Shrimp Pieces Cooked with our special charcoal flavor and with a delicious mix of lettuces, tomatoes, cucumber, Onions, Green Peppers, and the Sauce of your choice', 'Platter', 10.99, '/images/menu/7d.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (924, 'Fish Over Rice', 'Our large specially breaded two white fila fish cutlet served over rice with vegetable salad and the Sauce of your choice', 'Platter', 10.99, '/images/menu/7e.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (925, 'Fish Over Salad', 'Our large specially breaded two white fila fish cutlet served with lettuces, tomatoes, cucumber, and the Sauce of your choice', 'Platter', 10.99, '/images/menu/7f.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (926, 'Fish with Fries', 'Our large specially breaded two white fila fish cutlet served with our home seasoned fries, and the Sauce of your choice', 'Platter', 10.99, '/images/menu/7g.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (927, 'Plain Chicken Wings over Rice', 'Six Fresh Fried Wings served over rice with Vegetable Salad and the Sauce of your choice', 'Platter', 9.99, '/images/menu/8a.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (928, 'Buffalo Chicken Wings over Rice', 'Six Spicy Fried Wings made with our Special Buffalo Sauce served over rice with Vegetable Salad', 'Platter', 9.99, '/images/menu/8b.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (929, 'BBQ Chicken Wings Over Rice', 'Six BBQ Fried Wings made with our Special BBQ Sauce and Flavor served over rice with Vegetable Salad', 'Platter', 9.99, '/images/menu/8c.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (1027, '2-Liter Pepsi Soda', 'Two Litters Bottle of Pepsi', 'Drinks', 2.99, '/images/menu/pepsi-2liter.png', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (930, 'Plain Chicken Wings with Salad', 'Six Fresh Fried Wings served with Vegetable Salad and the Sauce of your choice', 'Platter', 9.99, '/images/menu/8.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (931, 'Buffalo Chicken Wings with Salad', 'Six Spicy Fried Wings made with our Special Buffalo Sauce served with Vegetable Salad+D66E65:F68F63A68:F68E64:F68D64:F68DA68:F68', 'Platter', 9.99, '/images/menu/12.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (932, 'BBQ Chicken Wings with Salad', 'Six BBQ Fried Wings made with our Special BBQ Sauce and Flavor served with Vegetable Salad', 'Platter', 9.99, '/images/menu/13.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (933, 'Plain Chicken Wings with Fries', 'Six Fresh Fried Wings served with our Special Seasoned French Fries and the Sauce of your choice', 'Platter', 9.99, '/images/menu/13b.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (934, 'Buffalo Chicken Wings with Fries', 'Six Spicy Fried Wings made with our Special Buffalo Sauce served with our Special Seasoned French Fries', 'Platter', 9.99, '/images/menu/13c.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (935, 'BBQ Chicken Wings with Fries', 'Six BBQ Fried Wings made with our Special BBQ Sauce and Flavor served  with our Special Seasoned French Fries', 'Platter', 9.99, '/images/menu/13d.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (936, 'Falafel over Rice', 'Eight Pieces of our special Homemade crispy fresh Falafel served over rice with Vegetable Salad and the Sauce of your choice', 'Platter', 9.99, '/images/menu/14.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (937, 'Falafel Salad', 'Eight Pieces of our special Homemade crispy fresh Falafel served with lettuces, tomatoes, cucumber, and the Sauce of your choice', 'Platter', 8.99, '/images/menu/15.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (938, 'Empanadas over rice and salad', 'Two Baby fried beef potato patties breaded  in Latin Style Served with Rice, Vegetable Salad and the Sauce of your choice', 'Platter', 10.99, '/images/menu/15b.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (939, '-Tuna Fish Salad', 'Our Special homemade fresh Tuna Fish with  with Mix of Vegetable Salad and the Sauce of your choice', 'Platter', 8.49, '/images/menu/15c.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (940, '-Tuna Fish Egg Salad Melt Deluxe', 'Grilled Eggs Over Our Special homemade fresh Tuna Fish with Mix of Vegetable Salad and the Sauce of your choice', 'Platter', 9.99, '/images/menu/15d.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (941, '-Turkey  Over Rice', 'Slices of Bold Salsalito Turkey Breast  over rice withmix of Vegetable Salad and the Sauce of your choice', 'Platter', 10.99, '/images/menu/15e.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (942, '-Turkey  with Halal Bacon', 'Slices of Bold Salsalito Turkey Breast with Halal Cured Sliced Beef or Turkey Bacon served with Onion, Green Peppers, lettuces, tomatoes, cucumber, and the Sauce of your choice and  the bread of your choice', 'Platter', 10.99, '/images/menu/15f.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (943, 'Italian Sausage over Rice', 'Extra Large Grilled Beef Italian Sausage cut in pieces served over rice with Vegetable Salad and the Sauce of your choice', 'Platter', 9.99, '/images/menu/16.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (944, 'Italian Sausage Salad', 'Extra Large Grilled Beef Italian Sausage cut in pieces served with lettuces, tomatoes, cucumber, and the Sauce of your choice', 'Platter', 9.99, '/images/menu/17.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (945, 'Double Chicken Shish kebab over Rice', 'Charcoal Grilled Chicken Chunks came off two Shish Kebab Sticks served over rice with Vegetable Salad and the Sauce of your choice', 'Platter', 9.99, '/images/menu/18.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (946, 'Double Chicken Shish Salad', 'Charcoal Grilled Chicken Chunks came off two Shish Kebab Sticks served with lettuces, tomatoes, cucumber, and the Sauce of your choice', 'Platter', 9.99, '/images/menu/19.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (947, 'Double Beef Shish kebab over Rice', 'Charcoal Grilled Chicken Chunks came off two Shish Kebab Sticks served over rice with Vegetable Salad and the Sauce of your choice', 'Platter', 9.99, '/images/menu/18b.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (948, 'Double Beef Shish Salad', 'Charcoal Grilled Chicken Chunks came off two Shish Kebab Sticks served with lettuces, tomatoes, cucumber, and the Sauce of your choice', 'Platter', 9.99, '/images/menu/19b.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (949, 'Eggs & Cheese & Salad', 'Two Grilled Eggs and Cheese served with Onion, Green Peppers, lettuces, tomatoes, cucumber, and the Sauce of your choice', 'Platter', 5.99, '/images/menu/20.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (950, 'Eggs s& Beef Berger & Salad', 'Two Grilled Eggs and Beef Berger served with Onion, Green Peppers, lettuces, tomatoes, cucumber, and the Sauce of your choice', 'Platter', 8.99, '/images/menu/21.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (951, 'Eggs & Hot Dog & Salad', 'Two Grilled Eggs with Pieces of Beef Hot Dog served with Onion, Green Peppers, lettuces, tomatoes, cucumber, and the Sauce of your choice', 'Platter', 7.99, '/images/menu/22.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (952, 'Halal Bacon and Sausage Salad Plate', 'Two Grilled Eggs and Cheese with Halal Cured Sliced Beef or Turkey Bacon served with Onion, Green Peppers, lettuces, tomatoes, cucumber, and the Sauce of your choice', 'Platter', 8.99, '/images/menu/22b.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (953, 'Eggs & Hot Sausage & Salad', 'Two Grilled Eggs with Pieces of Beef Hot Sausage served with Onion, Green Peppers, lettuces, tomatoes, cucumber, and the Sauce of your choice', 'Platter', 8.49, '/images/menu/23.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (954, 'Eggs & Italian Sausage & Salad', 'Two Grilled Eggs with Pieces of Large Beef Italian Sausage served with Onion, Green Peppers, lettuces, tomatoes, cucumber, and the Sauce of your choice', 'Platter', 9.99, '/images/menu/24.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (955, 'Chicken Gyro', 'Grilled chicken chunks with Vegetable Salad Wrapped in a Pita Bread and with the Sauce of your choice', 'Sandwich', 7.99, '/images/menu/25.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (956, 'Lamp Gyro', 'Lamp Gyro Slices just came off the Rotating Gyro Machine now with Vegetable Salad Wrapped in a Pita Bread and with the Sauce of your choice', 'Sandwich', 7.99, '/images/menu/26.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (957, 'Combo (lamp & Chicken)', 'Grilled Chunks of Chicken and Lamp Gyro with Vegetable Salad Wrapped in a Pita Bread and with the Sauce of your choice', 'Sandwich', 8.99, '/images/menu/27.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (958, 'Jumbo Shrimp Sandwich', 'grilled Fresh Jumbo Shrimp Pieces Cooked with our special charcoal flavor in your choice of Bread and Sauce', 'Sandwich', 8.99, '/images/menu/27b.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (959, 'Fish Fillet Sandwich', 'large specially breaded white fila fish in your choice of Bread and Sauce', 'Sandwich', 7.99, '/images/menu/27c.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (960, 'Falafel Sandwich', 'Eight Pieces of our special Homemade crispy fresh Falafel Wrapped in a Pita Bread and with the Sauce of your choice', 'Sandwich', 7.99, '/images/menu/28.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (961, 'Philly Cheese Steak', 'Fresh Philly Steak with Vegetable Salad and our special Wrapped in a Pita Bread and with the Sauce of your choice', 'Sandwich', 6.99, '/images/menu/29.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (962, 'Hot Dog', 'Grilled Beef Hot Dog in a Bun with the Sauce of your choice', 'Sandwich', 2.50, '/images/menu/30.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (963, 'Hot Sausage', 'Grilled Seasoned Beef Hot Sausage in a Bun with the Sauce of your choice', 'Sandwich', 3.50, '/images/menu/31.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (964, 'Italian Sausage', 'Extra Large Seasoned Beef Italian Hot Sausage with Vegetable Salad Wrapped in a Pita Bread and with the Sauce of your choice', 'Sandwich', 6.99, '/images/menu/32.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (965, 'Chicken Shish kebab', 'Charcoal Grilled Chicken Chunks came off a Shish Kebab Stick with Vegetable Salad Wrapped in a Pita Bread and with the Sauce of your choice', 'Sandwich', 5.99, '/images/menu/33.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (966, 'Double Chicken Shish kebab', 'Charcoal Grilled Chicken Chunks came off two Shish Kebab Sticks with Vegetable Salad Wrapped in a Pita Bread and with the Sauce of your choice', 'Sandwich', 8.99, NULL, true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (967, 'Beef Shish kebab', 'Charcoal Grilled Beef Chunks came off a Shish Kebab Stick with Vegetable Salad Wrapped in a Pita Bread and with the Sauce of your choice', 'Sandwich', 6.99, '/images/menu/34b.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (968, 'Double Beef Shish kebab', 'Charcoal Grilled Beef Chunks came off two Shish Kebab Sticks with Vegetable Salad Wrapped in a Pita Bread and with the Sauce of your choice', 'Sandwich', 9.99, NULL, true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (969, 'Beef Burger', 'Grilled Halal Guicy Beef Berger with Vegetable Salad in a Sandwich with the Sauce of your choice', 'Sandwich', 6.49, '/images/menu/35.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (970, 'Chickenf Burger', 'Grilled Halal Guicy Chicken Berger with Vegetable Salad in a Sandwich with the Sauce of your choice', 'Sandwich', 6.49, '/images/menu/35a.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (971, 'Cheese Beef Burger', 'Grilled Halal Guicy Beef Berger with American Cheese and Vegetable Salad in a Sandwich with the Sauce of your choice', 'Sandwich', 6.99, '/images/menu/35b.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (972, 'Cheese Chicken Burger', 'Grilled Halal Guicy Chicken Berger with American Cheese and Vegetable Salad in a Sandwich with the Sauce of your choice', 'Sandwich', 6.99, '/images/menu/35b2.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (973, 'Chopped Cheese Sandwich', 'Chopped Grilled Halal Beef Berger with American Cheese in a Hero and the Sauce of your choice', 'Sandwich', 7.99, '/images/menu/35c.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (974, 'Halal Bacon Sandwich', 'Halal Cured Sliced Beef or Turkey Bacon with or without American Cheese in a Roll with the Sauce of your choice', 'Sandwich', 5.99, '/images/menu/35d.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (975, 'Halal Bacon and Sausage Sandwich', 'Halal Cured Sliced Beef or Turkey Bacon with Pieces of a Seasoned Beef Hot Sausage with the bread and Sauce of your choice', 'Sandwich', 7.99, '/images/menu/35e.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (976, '-Tuna Fish Salad Sandwich', 'Our Special homemade fresh Tuna Fish with  with Vegetable Salad  in the bread of your choice', 'Sandwich', 8.49, '/images/menu/0h2.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (977, '-Tuna Fish Egg Salad Melt Deluxe Sandwich', 'Grilled Eggs Over Our Special homemade fresh Tuna Fish with Vegetable Salad  in the bread of your choice', 'Sandwich', 9.99, '/images/menu/0h3.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (978, '-Tuna Fish Salad over Turkey  Sandwich', 'Slices of Bold Salsalito Turkey Breast Over Our Special homemade fresh Tuna Fish with Vegetable Salad  in the bread of your choice', 'Sandwich', 10.99, '/images/menu/0h4.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (979, '-Turkey  Sandwich', 'Slices of Bold Salsalito Turkey Breast with  Vegetable Salad in  the bread of your choice', 'Sandwich', 8.99, '/images/menu/0h5.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (980, '-Turkey  with Halal Bacon Sandwich', 'Slices of Bold Salsalito Turkey Breast with Halal Cured Sliced Beef or Turkey Bacon served with Onion, Green Peppers, lettuces, tomatoes, cucumber, and the Sauce of your choice and  the bread of your choice', 'Sandwich', 8.99, '/images/menu/0h6.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (981, 'Bagel / Roll With Cream Chesse or Better', 'Fresh backed today Bagel or Roll with you favor Butter or Cream Cheese kind (It''s the Coffee Favor to make it a Breakfast)', 'Sandwich', 2.99, '/images/menu/35f.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (982, 'Eggs Sandwich', 'Two Grilled Eggs with Vegetable Salad in a Roll or Pita Bread with the Sauce of your choice', 'Sandwich', 2.99, '/images/menu/36.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (983, 'Cream Chesse Sandwich (Bagel / Roll / Croissant / Hero / More..)', 'Fresh backed today Bagel, Roll or your preferred kind of bread with our fresh Cream Cheese  (It''s the Coffee Favor to make it a Breakfast)', 'Sandwich', 2.99, '/images/menu/35f.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (984, 'Eggs Sandwich (Bagel / Roll / Croissant / Hero / Pita / More..)', 'Two Grilled Eggs with Vegetable Salad in your preferred kind of bread with the Sauce of your choice', 'Sandwich', 2.99, '/images/menu/36.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (985, 'Eggs & Cheese Sandwich (Bagel / Roll / Croissant / Hero / Pita / More..)', 'Two Grilled Eggs and Cheese with Vegetable Salad in your preferred kind of bread  with the Sauce of your choice', 'Sandwich', 3.99, '/images/menu/37.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (986, 'Eggs & Halal Bacon Sandwich (Bagel / Roll / Croissant / Hero / Pita / More..)', 'Two Grilled Eggs and Cheese with Halal Cured Sliced Beef or Turkey Bacon and Vegetable Salad in your preferred kind of bread with the Sauce of your choice', 'Sandwich', 5.99, '/images/menu/37b.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (987, 'Eggs & Beef Berger Sandwich (Bun / Bagel / More..)', 'Two Grilled Eggs and Beef Berger with Vegetable Salad in your preferred kind of bread with the Sauce of your choice', 'Sandwich', 7.99, '/images/menu/38.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (988, 'Eggs & Hot Dog Sandwich (Bun / Bagel / Croissant / Pita / More..)', 'Two Grilled Eggs and Pieces of a Beef Hot Dog with Vegetable Salad in your preferred kind of bread with the Sauce of your choice', 'Sandwich', 5.50, '/images/menu/39.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (989, 'Eggs & Sausage Sandwich  (Bun / Bagel / Croissant / Pita / More..)', 'Two Grilled Eggs and Pieces of a Seasoned Beef Hot Sausage with Vegetable Salad in your preferred kind of bread with the Sauce of your choice', 'Sandwich', 6.99, '/images/menu/40.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (990, 'Eggs & Cheese & Sausage Sandwich (Bun / Bagel / Croissant / Pita / More..)', 'Two Grilled Eggs and Pieces of a Seasoned Beef Hot Sausage with Vegetable Salad in your preferred kind of bread with the Sauce of your choice', 'Sandwich', 6.99, '/images/menu/40a.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (991, 'Eggs & Italian Sausage Sandwich (Bun / Bagel / Croissant / Pita / Hero / More..)', 'Two Grilled Eggs and Pieces of an Extra Large Seasoned Beef Italian Sausage with Vegetable Salad Wrapped in your preferred kind of bread with the Sauce of your choice', 'Sandwich', 8.99, '/images/menu/41.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (992, 'Beef Burger', 'Grilled Halal Guicy Beef Berger with Vegetable Salad in a Sandwich with the Sauce of your choice', 'Bergers', 6.49, '/images/menu/35.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (993, 'Beef Burger Deluxe', 'Grilled Halal Guicy Beef Berger with Vegetable Salad in a Sandwich with the Sauce of your choice, Frech Fries on the Side and a Can of Soda of your choice', 'Bergers', 6.49, '/images/menu/35a1.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (994, 'Double Beef Burger', 'Two Layers of Grilled Halal Guicy Beef Berger with Vegetable Salad in a Sandwich with the Sauce of your choice', 'Bergers', 6.49, '/images/menu/35a2.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (995, 'Double Beef Burger Deluxe', 'Two Layers of Grilled Halal Guicy Beef Berger with Vegetable Salad in a Sandwich with the Sauce of your choice, Frech Fries on the Side and a Can of Soda of your choice', 'Bergers', 6.49, '/images/menu/35a3.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (996, 'Chicken Burger', 'Grilled Halal Guicy Chicken Berger with Vegetable Salad in a Sandwich with the Sauce of your choice', 'Bergers', 6.49, '/images/menu/35a.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (997, 'Chicken Burger Deluxe', 'Grilled Halal Guicy Chicken Berger with Vegetable Salad in a Sandwich with the Sauce of your choice, Frech Fries on the Side and a Can of Soda of your choice', 'Bergers', 6.49, '/images/menu/35a4.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (998, 'Double Chicken Burger', 'Two Layers of Grilled Halal Guicy Chicken Berger with Vegetable Salad in a Sandwich with the Sauce of your choice', 'Bergers', 6.49, '/images/menu/35a5.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (999, 'Cheese Beef Burger', 'Grilled Halal Guicy Beef Berger with American Cheese and Vegetable Salad in a Sandwich with the Sauce of your choice', 'Bergers', 6.99, '/images/menu/35b.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (1000, 'Cheese Chicken Burger', 'Grilled Halal Guicy Chicken Berger with American Cheese and Vegetable Salad in a Sandwich with the Sauce of your choice', 'Bergers', 6.99, '/images/menu/35b2.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (1001, 'Eggs & Beef Berger Sandwich', 'Two Grilled Eggs and Beef Berger with Vegetable Salad in a Roll or Pita Bread with the Sauce of your choice', 'Bergers', 7.99, '/images/menu/38.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (1002, 'Eggs & Chicken Berger Sandwich', 'Two Grilled Eggs and Chicken Berger with Vegetable Salad in a Roll or Pita Bread with the Sauce of your choice', 'Bergers', 7.99, '/images/menu/38b.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (1003, 'Eggs s& Beef Berger & Salad Plate', 'Two Grilled Eggs and Beef Berger served with Onion, Green Peppers, lettuces, tomatoes, cucumber, and the Sauce of your choice', 'Bergers', 8.99, '/images/menu/21.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (1004, 'Eggs s& Beef Berger & Salad', 'Two Grilled Eggs and Beef Berger served with Onion, Green Peppers, lettuces, tomatoes, cucumber, and the Sauce of your choice', 'Bergers', 8.99, '/images/menu/21.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (1005, 'Habibi Jerk Plate', 'Chopped Boneless Jerk Charcoal Grilled Chicken Chunks with melted cheese and fries with the Sauce of your choice', 'Habibi Specials', 4.99, '/images/menu/42a.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (1006, 'Chicken Shish kebab Stick', 'Charcoal Grilled Chicken Chunks in a Shish Kebab Stick with the Sauce of your choice', 'Extras', 4.99, '/images/menu/42.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (1007, 'Beef Shish kebab Stick', 'Charcoal Grilled Beef Chunks in a Shish Kebab Stick with the Sauce of your choice', 'Extras', 5.99, '/images/menu/42b.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (1008, 'Pita Bread with White Sauce and Garlic', 'Our Delicious Pita Bread heated and cut on the Grill with our Special White Sauce', 'Extras', 1.50, '/images/menu/43.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (1009, 'French Fries', 'Fresh French Fries with the Sauce of your choice', 'Extras', 2.99, '/images/menu/44.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (1010, 'French Fries Plate (Large)', 'A Large Plate of Fresh French Fries with the Sauce of your choice', 'Extras', 4.99, '/images/menu/45.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (1011, 'Rice Plate', 'Our Special Seasoned Rice with the Sauce of your choice', 'Extras', 3.49, '/images/menu/46.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (1012, 'Double Rice Plate', 'A Large Plate of our Special Seasoned Rice with the Sauce of your choice', 'Extras', 4.99, '/images/menu/47.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (1013, '4 Falafel with White Sauce', 'Eight Pieces of our special Homemade crispy fresh Falafel with our Special White Sauce', 'Extras', 3.50, '/images/menu/48.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (1014, 'Side Salad Mix Plate', 'A Fresh Healthy Side Plate with a delicious mix of lettuces, tomatoes, cucumber, Onions, Green Peppers, and the Sauce of your choice', 'Extras', 5.99, '/images/menu/48b.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (1015, 'Samosa (As Many as You want)', 'One piece of fried pastry with a savory stuffing', 'Extras', 1.00, '/images/menu/49.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (1016, 'Empanada (As Many as You want)', 'Baby fried beef potato pattie breaded in Latin Style  with the Sauce of your choice', 'Extras', 3.99, '/images/menu/49a.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (1017, 'Mozzarella Sticks', 'Six Pieces of our Home-Made Style Fried Mozzarella Cheese Sticks Served with the Sauce of your choice', 'Extras', 6.99, '/images/menu/49b.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (1018, 'Onion Rings', 'Homemade Onion Rings; Fried to be Super Crispy Easy and Delicious', 'Extras', 4.99, '/images/menu/49c.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (1019, 'Donut', 'Select Between Varity of Fresh Backed Today Donuts!', 'Extras', 1.99, '/images/menu/49d.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (1020, 'Dozen Donuts', 'A Mix of 12 Fresh Today Backed  Donuts', 'Extras', 13.99, '/images/menu/49d2.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (1021, 'Croissant', 'fresh Backed today Croissant', 'Extras', 2.49, '/images/menu/49e.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (1022, 'Muffin', 'fresh Backed today Muffin of your choice', 'Extras', 2.99, '/images/menu/49f.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (1023, 'Danish', 'Fresh Backed Today Danish of your Choice between Cheese and Cinnamon Kind', 'Extras', 2.99, '/images/menu/49g.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (1024, 'Apple Turnover', 'A pastry dessert filled with pieces of sweetened apples and Freshly Backed Today', 'Extras', 2.99, '/images/menu/49h.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (1025, 'Chocolate Cake', 'A soft fresh prepared Cake Slice ranged from light and fluffy to creamy, thick  give it a light and airy texture, sweet and savory Taste', 'Extras', 3.99, '/images/menu/49i.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (1026, 'Canned Soda', 'A Soda Can of your choice from Pepsi, Diet Pepsi, Coke, Orange, Sprite, Ginger Gle, or Iced Tea', 'Drinks', 1.49, '/images/menu/50.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (1028, 'Bottled  Water', 'Poland Spring Bottle of Water 16.9 Fl oz', 'Drinks', 1.49, '/images/menu/52.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (1029, 'Snapple', 'A Snapple Juice Bottle of your flavor choice from Apple, Lemon Tea, and Peach', 'Drinks', 2.99, '/images/menu/53.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (1030, 'Gatorade', 'Gatorade Classic Thirst Quencher with various flavors of your flavor choice from Lemon Lime, Orange, Fruit Punch, Berry', 'Drinks', 2.99, '/images/menu/54.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (1031, 'Orange Juice', 'Fresh Orange Juice packaged by US', 'Drinks', 2.99, '/images/menu/55.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (1032, 'Apple Juice', 'Fresh Apple Juice packaged by US', 'Drinks', 2.99, '/images/menu/56.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (1033, 'Cranberry Juice', 'Fresh Cranberry Juice packaged by US', 'Drinks', 2.99, '/images/menu/57.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (1034, 'Pineapple Juice', 'Fresh Pineapple  Juice packaged by US', 'Drinks', 2.99, '/images/menu/58.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (1035, 'Mix Juice', 'Mix any kind of two or more of our fresh Juices  packaged by US Just for you', 'Drinks', 3.99, '/images/menu/59.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (1036, 'Ice Coffee', 'Highest Quality of Colombian Coffee made with our special commercial coffee machine with your flavor choice and the right amount of sugar, Ice and size', 'Drinks', 2.99, '/images/menu/60.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (1037, 'Regular Hot Coffee', 'Highest Quality of Colombian Coffee made with our special commercial coffee machine with your flavor choice and the right amount of sugar and size', 'Drinks', 2.49, '/images/menu/61.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (1038, 'Hot Chocolate', 'Highest Quality of our special Home-Made Style hot Chocolate with your choice of the right amount of sugar', 'Drinks', 2.49, '/images/menu/62.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (1039, 'Tea', 'Drink our special home-made tea like never before with your kind choice and the right amount of sugar, Size and Add-Ons', 'Drinks', 2.49, '/images/menu/63.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (1040, 'Chicken over Rice Family Tray', 'Grilled chicken chunks served over rice with vegetable salad and the Sauces of your choice more than enough for four people', 'Family Tray', 31.99, '/images/menu/64.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (1041, 'Lamp over Rice Family Tray', 'Lamp Gyro Slices just came off the Rotating Gyro Machine now served over rice with vegetable salad and the Sauces of your choice more than enough for four people', 'Family Tray', 31.99, '/images/menu/65.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (1042, 'Combo (lamp & Chicken) over Rice Family Tray', 'Grilled Chunks of Chicken and Lamp Gyro served over rice with vegetable salad and the Sauces of your choice more than enough for four people', 'Family Tray', 34.99, '/images/menu/66.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (1043, 'Whole Chicken Over Rice', 'Our Grilled Specially Seasoned Whole Large Chicken on the bone (Cutted in Four Pieces) and served over rice with vegetable salad and the Sauce of your choice', 'Family Tray', 24.99, '/images/menu/66b.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (1044, 'Jumbo Shrimp Over Rice Family Tray', 'Grilled Fresh Jumbo Shrimp Pieces Cooked with our special charcoal flavor and served over rice with vegetable salad and the Sauces of your choice more than enough for four people', 'Family Tray', 36.99, '/images/menu/67.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (1045, 'Fish Over Rice Family Tray', 'Our large specially breaded eight white fila fish cutlet served over rice with vegetable salad and the Sauces of your choice more than enough for four people', 'Family Tray', 36.99, '/images/menu/68.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (1046, 'Chicken Wings over Rice Family Tray', '24 Fresh Fried Wings served over rice with Vegetable Salad and the Sauces of your choice, more than enough for four people, Whether you like it Buffalo, Plain, or BBQ', 'Family Tray', 31.99, '/images/menu/69.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (1047, 'Eggs & Hot Sausage & Salad Family Tray', 'Six Grilled Eggs with Pieces of Beef Hot Sausage served with Onion, Green Peppers, lettuces, tomatoes, cucumber, and the Sauces of your choice more than enough for four people', 'Family Tray', 29.99, '/images/menu/70.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);
INSERT INTO public.menus VALUES (1048, 'Dozen Donuts', 'A Mix of 12 Fresh  Backed Today Donuts', 'Family Tray', 13.99, '/images/menu/49d2.jpg', true, '2026-05-19 20:27:03.669272', '[]', '[]', '[]', 'neutral', '[]', NULL, 0, NULL, true, NULL, NULL, false, false, false);


--
-- Name: addon_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.addon_groups_id_seq', 42, true);


--
-- Name: addon_options_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.addon_options_id_seq', 126, true);


--
-- Name: categories_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.categories_id_seq', 13, true);


--
-- Name: choice_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.choice_groups_id_seq', 42, true);


--
-- Name: choice_options_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.choice_options_id_seq', 126, true);


--
-- Name: menu_items_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.menu_items_id_seq', 211, true);


--
-- Name: menus_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.menus_id_seq', 1048, true);


--
-- PostgreSQL database dump complete
--

\unrestrict lds7PO5Qgi97BZaA97yDyFo5Won7dxBUf4eBsrvC5yyymabgvVNwvtWIoS1ALVM

